# Generated by Django 6.0.4 on 2026-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0019_etablissement_adresse_etablissement_agrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Estim Campus', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo (upload)')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo (URL externe)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Logo / Branding de l'app",
                'verbose_name_plural': "Logo / Branding de l'app",
            },
        ),
        migrations.CreateModel(
            name='OnboardingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='onboarding/', verbose_name='Image (upload)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image (URL externe)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Slide d'onboarding",
                'verbose_name_plural': "Slides d'onboarding",
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
