# Generated by Django 6.0.4 on 2026-09-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0020_appbranding_onboardingslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='campusapp',
            options={'verbose_name': 'Application campus', 'verbose_name_plural': 'Applications campus'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'verbose_name': 'Établissement', 'verbose_name_plural': 'Établissements'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Examens'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'verbose_name': "Image d'accueil", 'verbose_name_plural': "Images d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'verbose_name': 'Résultat', 'verbose_name_plural': 'Résultats'},
        ),
        migrations.AlterModelOptions(
            name='sessionexamen',
            options={'verbose_name': "Session d'examen", 'verbose_name_plural': "Sessions d'examen"},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
