# Generated by Django 6.0.4 on 2026-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0021_alter_annonce_options_alter_campusapp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thème principal', max_length=100)),
                ('primary_color', models.CharField(default='#7c3aed', max_length=7, verbose_name='Couleur principale (hex, ex : #1a6b3c)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Thème de l'admin",
                'verbose_name_plural': "Thèmes de l'admin",
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='etablissements/', verbose_name="Image / logo de l'établissement"),
        ),
    ]
