# Generated by Django 6.0.4 on 2026-09-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0022_themeconfig_etablissement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=20, verbose_name='Destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('SUCCESS', 'Envoyé'), ('FAILED', 'Échoué'), ('SKIPPED', 'Ignoré')], default='FAILED', max_length=10)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Réponse API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message WhatsApp',
                'verbose_name_plural': 'Journal WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence du reçu')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule étudiant')),
                ('nom_etudiant', models.CharField(max_length=200, verbose_name="Nom de l'étudiant")),
                ('motif', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('EXAMEN', "Frais d'examen"), ('AUTRE', 'Autre')], default='SCOLARITE', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('methode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('AUTRE', 'Autre')], default='ESPECES', max_length=15, verbose_name='Méthode')),
                ('phone_tuteur', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° tuteur (SMS)')),
                ('recu_par', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reçu par (agent)')),
                ('sms_envoye', models.BooleanField(default=False, verbose_name='SMS envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
            ],
            options={
                'verbose_name': 'Paiement scolarité',
                'verbose_name_plural': 'Paiements scolarité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personnel', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('ADMINISTRATIF', 'Administratif')], default='ENSEIGNANT', max_length=15, verbose_name='Type de personnel')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom(s)')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom(s)')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('fonction', models.CharField(max_length=255, verbose_name='Fonction / Poste')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base (FCFA)')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/photos/', verbose_name='Photo')),
                ('cv', models.FileField(blank=True, null=True, upload_to='employes/docs/', verbose_name='CV')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='employes/docs/', verbose_name='Diplôme')),
                ('contrat', models.FileField(blank=True, null=True, upload_to='employes/docs/', verbose_name='Contrat de travail')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='employes/docs/', verbose_name="Pièce d'identité")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.etablissement', verbose_name='Établissement')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.filiere', verbose_name="Filière d'affectation")),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.employe', verbose_name='Enseignant assigné'),
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base (FCFA)')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Primes (FCFA)')),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retenues (FCFA)')),
                ('verse_le', models.DateField(blank=True, null=True, verbose_name='Versé le')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='campus.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
