# Generated by Django 6.0.4 on 2026-09-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0023_messagelog_paiementscolarite_employe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='montant_scolarite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant scolarité (FCFA)'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='montant_scolarite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant scolarité (FCFA)'),
        ),
        migrations.AddField(
            model_name='paiementscolarite',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='paiementscolarite',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.niveau', verbose_name='Niveau'),
        ),
    ]
