# Generated by Django 6.0.4 on 2026-09-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_filiere_montant_scolarite_niveau_montant_scolarite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='2025-2026', max_length=20, unique=True, verbose_name='Année (ex : 2025-2026)')),
                ('mois_debut', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=10, verbose_name='Mois début des cours')),
                ('mois_fin', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=6, verbose_name='Mois fin des cours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Année en cours')),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-nom'],
            },
        ),
    ]
