# Generated by Django 6.0.4 on 2026-09-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0025_anneeacademique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.filiere', verbose_name='Filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Tarif scolarité (Filière + Niveau)',
                'verbose_name_plural': 'Tarifs scolarité (Filière + Niveau)',
                'unique_together': {('filiere', 'niveau')},
            },
        ),
    ]
