# Generated by Django 6.0.4 on 2026-09-27 14:29

from django.db import migrations, models


def copy_days_forward(apps, schema_editor):
    Cours = apps.get_model("campus", "Cours")
    for c in Cours.objects.all():
        try:
            c.jours = str(int(c.day_of_week))
        except (TypeError, ValueError):
            c.jours = "1"
        c.save(update_fields=["jours"])


def copy_days_backward(apps, schema_editor):
    Cours = apps.get_model("campus", "Cours")
    for c in Cours.objects.all():
        try:
            c.day_of_week = int(str(c.jours or "1").split(",")[0])
        except (TypeError, ValueError):
            c.day_of_week = 1
        c.save(update_fields=["day_of_week"])


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_tarifscolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='jours',
            field=models.CharField(default='1', help_text='Plusieurs jours séparés par des virgules, ex : 1,3,5 (1=Lundi … 7=Dimanche)', max_length=13, verbose_name='Jours de la semaine'),
        ),
        migrations.RunPython(copy_days_forward, copy_days_backward),
        migrations.RemoveField(
            model_name='cours',
            name='day_of_week',
        ),
    ]
