# Generated by Django 6.0.4 on 2026-09-28 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0027_remove_cours_day_of_week_cours_jours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='accent_color',
            field=models.CharField(default='#f5a623', max_length=7, verbose_name="Couleur d'accent (hex, ex : #f5a623)"),
        ),
        migrations.CreateModel(
            name='ProfilEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.etablissement', verbose_name='Établissement géré')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etablissement', to=settings.AUTH_USER_MODEL, verbose_name='Compte admin')),
            ],
            options={
                'verbose_name': "Admin d'établissement",
                'verbose_name_plural': "Admins d'établissement",
            },
        ),
    ]
