# Generated by Django 6.0.4 on 2026-09-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0028_themeconfig_accent_color_profiletablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementscolarite',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='paiementscolarite',
            name='mois',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text="Mois de scolarité couvert par ce paiement (limité à la période de l'année académique).", null=True, verbose_name='Mois concerné'),
        ),
    ]
