# Generated by Django 6.0.4 on 2026-09-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0029_paiementscolarite_annee_academique_and_more'),
        ('campus', '0029_remove_niveau_montant_scolarite'),
    ]

    operations = [
    ]
