# Generated by Django 6.0.4 on 2026-09-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_etablissement_to_m2m(apps, schema_editor):
    Profil = apps.get_model("campus", "ProfilEtablissement")
    for p in Profil.objects.all():
        try:
            if p.etablissement_id:
                p.etablissements.add(p.etablissement_id)
        except Exception:
            pass


def copy_etablissement_back(apps, schema_editor):
    Profil = apps.get_model("campus", "ProfilEtablissement")
    Etablissement = apps.get_model("campus", "Etablissement")
    for p in Profil.objects.all():
        first = p.etablissements.order_by("nom").first()
        if first:
            p.etablissement = first
            p.save(update_fields=["etablissement"])


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0030_merge_20260928_1029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletablissement',
            name='etablissements',
            field=models.ManyToManyField(blank=True, to='campus.etablissement', verbose_name='Écoles gérées'),
        ),
        migrations.RunPython(copy_etablissement_to_m2m, copy_etablissement_back),
        migrations.RemoveField(
            model_name='profiletablissement',
            name='etablissement',
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_employe', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion'),
        ),
        migrations.AddField(
            model_name='notification',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.etablissement', verbose_name='Établissement cible'),
        ),
        migrations.AddField(
            model_name='notification',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.filiere', verbose_name='Filière cible'),
        ),
        migrations.AddField(
            model_name='notification',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.niveau', verbose_name='Niveau cible'),
        ),
    ]
