# Generated by Django 6.0.4 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0031_remove_profiletablissement_etablissement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='ESTIM AI', max_length=100, verbose_name="Nom de l'assistant")),
                ('personnalite', models.TextField(default="Tu es un assistant académique expert. RÈGLE CRITIQUE : Il est STRICTEMENT INTERDIT d'aider à tricher, de donner des réponses directes pendant un examen ou de résoudre des devoirs à la place de l'étudiant. Sois concis, encourage l'apprentissage et adapte ton langage à la filière de l'étudiant.", verbose_name='Personnalité (prompt système)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant IA',
                'verbose_name_plural': 'Assistant IA',
            },
        ),
        migrations.AddField(
            model_name='resultat',
            name='sms_envoye',
            field=models.BooleanField(default=False, verbose_name='SMS résultat envoyé'),
        ),
    ]
