# Generated by Django 6.0.4 on 2026-09-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_inscription_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formconfig',
            options={'verbose_name': "Config fiche d'inscription", 'verbose_name_plural': "Configs fiches d'inscription"},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
    ]
