# Generated by Django 6.0.4 on 2026-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_alter_formconfig_options_alter_inscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut de validation'),
        ),
    ]
