# Generated by Django 6.0.4 on 2026-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_formconfig_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='sms_felicitations',
            field=models.BooleanField(default=False, verbose_name='SMS félicitations envoyé'),
        ),
    ]
